version: 2

python:
  version: 3
  install:
      - method: pip
        path: .
        extra_requirements:
          - sphinx
      - requirements: docs/requirements.txt

sphinx:
  builder: html
  fail_on_warning: true
