Search.setIndex({
  docnames: ["first-file", "intro", "second-file"],
  envversion: {
    "sphinx.domains.c": 2,
    "sphinx.domains.changeset": 1,
    "sphinx.domains.citation": 1,
    "sphinx.domains.cpp": 5,
    "sphinx.domains.index": 1,
    "sphinx.domains.javascript": 2,
    "sphinx.domains.math": 2,
    "sphinx.domains.python": 3,
    "sphinx.domains.rst": 2,
    "sphinx.domains.std": 2,
    "sphinx.ext.intersphinx": 1,
    sphinx: 56,
  },
  filenames: ["first-file.md", "intro.md", "second-file.md"],
  objects: {},
  objnames: {},
  objtypes: {},
  terms: {
    build: 1,
    folder: 1,
    just: 1,
    out: 1,
    sbt: 1,
    suit: 1,
    thi: [0, 1, 2],
  },
  titles: [
    "First File",
    "Jupyter-book test for sphinx-book-theme",
    "Second File",
  ],
  titleterms: {
    book: 1,
    file: [0, 2],
    first: 0,
    jupyt: 1,
    second: 2,
    sphinx: 1,
    test: 1,
    theme: 1,
  },
});
