
name: linkcheck
on:
  schedule:
    # Run on the first day of each week
    - cron:  '0 0 * * 1'
  workflow_dispatch:

jobs:
  # Build the docs and check for broken links.
  linkcheck:
    runs-on: ubuntu-latest
    name: Build documentation and check links
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        cache: "pip"
        cache-dependency-path: "pyproject.toml"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[doc]
    - name: Build documentation
      run: >
        sphinx-build -b html docs docs/_build/html -w warnings.txt
    # Ref: https://github.com/lycheeverse/lychee-action
    # Excluded files:
    # - nature.com: DOI redirect works but errors anyway
    # - doi.org: DOI redirect works but errors anyway
    # - yahoo.com: Kitchen sink redirect we don't control
    # - someurl: dummy url
    # - mailto: fails test but works for people
    # - pathto(: because the pydata theme packages invalid HTML w/ this in it
    # - mybinder.org: because Binder sometimes incorrectly doesn't respond
    # - github.com/search: because GitHub search results return a network error
    # - fastly: because these are programmatically generated links that break
    - name: Check for broken links
      id: lychee
      uses: lycheeverse/lychee-action@v1.4.1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        args: >
          './docs/_build/html/**/*.html'
          --exclude 'nature.com'
          --exclude 'doi.org'
          --exclude 'yahoo.com'
          --exclude 'someurl'
          --exclude 'mailto:docutils-develop'
          --exclude 'pathto\('
          --exclude 'mybinder.org'
          --exclude 'github.com/search'
          --exclude 'fastly'


    - name: Create Issue From File
      if: steps.lychee.outputs.exit_code != 0
      uses: peter-evans/create-issue-from-file@v3
      with:
        title: Link Checker Report
        content-filepath: ./lychee/out.md
        labels: bug, documentation
